language: python            # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.6
    - name: "Python 3.6 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: choco install python
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
install: pip3 install --upgrade pip