language: python            # this works for Linux but is an error on macOS or Windows
python:
  - "3.6"
  - "3.7-dev"

install:
  # Initial preparation
  - pip3 install --upgrade pip
  - pip3 install coverage
  - pip3 install coveralls
  - pip3 install .
  - pip3 install -r requirements.txt
script:
  - coverage run -m unittest discover tests/
after_success:
  - coveralls